import Link from "next/link";
import { requireOrgUser, getMyRoles } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { PageHeader } from "@/components/app/page-header";
import { SectionCard } from "@/components/app/section-card";
import { StatusBadge } from "@/components/app/status-badge";
import { ReasonDialog } from "@/components/app/reason-dialog";
import { ActionForm } from "@/app/_components/ActionForm";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { approvePackage, closePackage } from "../../actions";
import { SlideList, QuestionList, type Slide, type Question } from "./review-editor";
import { AssignDialog } from "./assign-dialog";

// T-REVIEW — the human gate (plan §1.1, §10). The trainer polishes the AI
// draft (inline edit, drag-and-drop) and APPROVES; only then can it be
// assigned. Approved content is frozen; provenance (AI draft vs approved
// text) is retained on every row.
export default async function PackageReview({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  await requireOrgUser();
  const roles = await getMyRoles();
  const isTrainer = roles.includes("qa") || roles.includes("trainer");
  const supabase = await createClient();

  const { data: pkg } = await supabase
    .from("training_packages")
    .select("id, document_id, document_version_id, template_key, question_count, pass_mark, state, source_text, approved_at, created_at")
    .eq("id", id)
    .maybeSingle();

  if (!pkg || !isTrainer) {
    return (
      <main className="mx-auto max-w-3xl p-2">
        <p className="text-sm text-muted-foreground">Package not found or trainer/QA only.</p>
      </main>
    );
  }

  const [{ data: doc }, { data: slides }, { data: questions }, { data: users }, { data: departments }, { data: aiLog }] =
    await Promise.all([
      supabase.from("documents").select("document_number, title").eq("id", pkg.document_id).maybeSingle(),
      supabase.from("training_slides").select("id, position, title, body, ai_draft").eq("package_id", id).order("position"),
      supabase.from("training_questions").select("id, position, question, options, correct_index, explanation, ai_draft").eq("package_id", id).order("position"),
      supabase.from("users").select("id, email, full_name").eq("status", "active").eq("plane", "org").order("email"),
      supabase.from("departments").select("id, name").order("name"),
      supabase.from("ai_gateway_log").select("provider, model_version, status, requested_at").eq("package_id", id).order("requested_at", { ascending: false }).limit(1),
    ]);

  const editable = pkg.state === "draft_review";
  const provenance = aiLog?.[0];

  return (
    <main className="mx-auto max-w-3xl space-y-6 p-2">
      <PageHeader
        overline={`${doc?.document_number ?? "—"} · ${pkg.template_key}`}
        title={`Training: ${doc?.title ?? "package"}`}
        description={
          editable
            ? "Polish the draft — click any text to edit, drag the handles to reorder. Nothing reaches a trainee until you approve."
            : undefined
        }
        actions={
          <div className="flex items-center gap-2">
            <StatusBadge value={pkg.state} kind="training" />
            <Button variant="outline" size="sm" asChild>
              <Link href={`/training/packages/${pkg.id}/preview`}>Preview as trainee</Link>
            </Button>
            {editable && (
              <ActionForm action={approvePackage} submitLabel="Approve package">
                <input type="hidden" name="package_id" value={pkg.id} />
              </ActionForm>
            )}
            {(pkg.state === "approved" || pkg.state === "assigned") && (
              <AssignDialog
                packageId={pkg.id}
                users={(users ?? []).map((u) => ({ id: u.id, label: u.full_name ?? u.email }))}
                departments={departments ?? []}
              />
            )}
            <ReasonDialog
              trigger={<Button variant="outline" size="sm">Close…</Button>}
              title="Close package"
              description="Withdraw this package (superseded version, defective content…). Assignments stop counting toward the threshold."
              action={closePackage}
              submitLabel="Close package"
              destructive
              hiddenFields={{ package_id: pkg.id }}
            />
          </div>
        }
      />

      {provenance && (
        <Alert>
          <AlertDescription>
            AI provenance: generated by <span className="font-medium">{provenance.provider} / {provenance.model_version}</span>{" "}
            ({provenance.status}) — drafts remain on record beside every human edit.
            {pkg.state === "approved" || pkg.state === "assigned"
              ? " Approval completed the provenance chain."
              : " Your approval completes the provenance chain."}
          </AlertDescription>
        </Alert>
      )}
      {!provenance && editable && (
        <Alert>
          <AlertDescription>
            No AI draft landed (generation failed or was skipped) — author the slides and questions
            manually below, or regenerate from the packages screen.
          </AlertDescription>
        </Alert>
      )}

      <SectionCard
        title={`Slides (${slides?.length ?? 0})`}
        description={editable ? "Trainees see these in order, with resume support." : "Approved deck (frozen)."}
      >
        <SlideList packageId={pkg.id} slides={(slides ?? []) as Slide[]} editable={editable} />
      </SectionCard>

      <SectionCard
        title={`Assessment (${questions?.length ?? 0} questions)`}
        description={
          editable
            ? "Every question must be answerable from the document itself — delete or regenerate any that are not."
            : "Approved question set (frozen). Correct answers never leave the server."
        }
      >
        <QuestionList packageId={pkg.id} questions={(questions ?? []).map((q) => ({
          ...q,
          options: (q.options ?? []) as string[],
        })) as Question[]} editable={editable} />
      </SectionCard>

      <div className="flex items-center justify-between text-xs text-muted-foreground">
        <span>
          Pass mark: <Badge variant="outline">{pkg.pass_mark ?? "tenant default"}</Badge>
        </span>
        <Link className="underline" href="/training/packages">
          ← All packages
        </Link>
      </div>
    </main>
  );
}
